# Site wide configuration

title: Shawn Mclean
description: "Software Engineering is fun"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
disqus-shortname: shawnmclean
url: ''

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
paginate: 5
paginate_path: "page-:num"

# Site owner
owner:
  name: Shawn Mclean
  web: http://shawnmclean.com
  email: shawnrmclean@gmail.com
  twitter: shawnrmclean
  bio: "Software Engineer, I write, test and deploy the codes."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +MichaelRoseDesign
    ad-client: ca-pub-7328585512091257
    ad-slot: 3049671934
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
